### ISSUE TITLE
Adjust dynamicEnum and availabilityChecks to new configuration format

### ISSUE THREAD

**Issue by manuelroth** [nzzdev/Q-election-seats#59]
### Task

We made changes to the configuration format of `dynamicEnums` and `availabilityChecks`. The schema and corresponding routes need to be adjusted as following (more details on the config format can be found [here](https://github.com/nzzdev/Q-editor/blob/dev/README.md)):

#### DynamicEnums
Current:
```json
"dynamicEnum": {
  "type": "ToolEndpoint",
  "withData": true,
  "endpoint": "dynamic-enum/selectedColumn"
}
```

New:
```json
"dynamicEnum": {
  "type": "ToolEndpoint",
  "config": {
    "endpoint": "dynamic-enum/selectedColumn",
    "fields": ["options", "data"]
  }
}
```
Additionally the `/dynamic-enum` now receives an object containing the `item` and optionally and `options` property. The route needs to be adjusted to this.

#### AvailabilityChecks
Current:
```json
{
  "type": "ToolEndpoint",
  "withData": true,
  "endpoint": "option-availability/invertColors"
}
```

New:
```json
{
  "type": "ToolEndpoint",
  "config": {
    "endpoint": "option-availability/invertColors",
    "data": ["options", "data"]
  } 
}
```

Additionally the `/option-availability` now receives an object containing the `item` and optionally and `options` property. The route needs to be adjusted to this.

**Comment by philipkueng** [comment]
This tool doesn't contain any endpoints which would need to be altered.

**Comment by manuelroth** [comment]
@philipkueng this tool has availabilityChecks which need to be updated -> https://github.com/nzzdev/Q-election-seats/blob/dev/resources/schema.json#L45
